name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: order-ms.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Add  MSBuild to the PATH
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Navigate to the subfolder
      - name: Change to project directory
        run: cd order-ms

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      # Build and test the application
      - name: Build and test
        run: dotnet build --configuration ${{ matrix.configuration }} && dotnet test --no-build --verbosity normal
        env:
          Configuration: ${{ matrix.configuration }}

      # Publish the application
      - name: Publish
        run: dotnet publish --configuration ${{ matrix.configuration }} --output ./publish
        env:
          Configuration: ${{ matrix.configuration }}

      # Upload the published application as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Published Application
          path: ./publish